dist: trusty
sudo: false
git:
  depth: false
env:
  global:
    - CC_TEST_REPORTER_ID=53eef44d00d3465aeaf806ea310cfc5497e7473d13ae05fbc753890c39712c60
addons:
  sonarcloud:
    organization: "lucacappelletti94-github"
    token:
      secure: "M5469GbYINSW3bn7LjWKMaqiUCcGxvPu/s3wXpZAVEUBFk/lKcPrO43JWyuOVve4NjHkqx+seyZqe9Fyer5tu+pMitBs1qrE8irWtj37hjbxW4rHDtq0mAKKkWA1n/vw4Xc2kd3897adKCbmr4daDMiDYrnEDb5bFYIK9q4nZ6qIDcZtvN02wh19aUdimpQQ9k1kDbYcHWoMkg7NoybigLA4tRcP4osOpmbcvr8rQFwFHDSnyr14oQvPDw+z30K5NZoqy1SfC68QOf3yZ3NNBoJ34jTvRYEfXLFvrlY8hUSJzNl8EGIi7w0eH0uiwDtQgGFbum7H8EH3S5ty+Ic44XIO01N/kEub2rNOrGDPFeRYptDrmIdjNkYmUFO4rR40AK7TW/kYgezHWWnN6q39/d0/g5LDuKtWz0/t7Ii/hCsUD8zQjexNoteXBaVvyz1uuDYofq6YWZ2A9KkMrkPV3rprPr5/a84QV43tqmbn3Xl/9fl/7BsGPUa5wJucyNgZXNUfcF3n344eJbGAmNqgxINd1hjj4vByX4Ocyk9cPe6jdLhEOtalMsWIQnZkDeX+K7RF8y6f1YBE8NyImNkoaD3rqywhSBnur9o7LNTHMmm3VmMeIcoq/gj4B8paa3cGuFsiGug7FPbvSEQjUAQBkZdx3D8MqNIIErek+GnUEBI="
language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
  - pip install tensorflow
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=gaussian_process --cov-report xml:coverage.xml 
- coverage combine --append
- coverage report
- coverage xml
- sonar-scanner

after_success:
  - coveralls